### ISSUE TITLE
Mega2R package obsolete

### ISSUE THREAD

**Issue by fabiennejh** [DanielEWeeks/PedGFLMM#1]
Hello,

The Mega2R package is not available for R 3.6 version. is it possibe for you to update it ?
Or with which version of R PedGFLMM would work ?

Thank you
Best
Fabienne

**Comment by DanielEWeeks** [comment]
Dear Fabienne,

Unfortunately I wasn't aware that Mega2R had been archived from CRAN.  I'll see if I can restore it.

In the meantime, the source code for Mega2R is available here:

https://bitbucket.org/dweeks/mega2r/src/master/

as well as in the archive section of CRAN:

https://cran.r-project.org/src/contrib/Archive/Mega2R/

Sorry for the inconvenience,
Dan

**Comment by DanielEWeeks** [comment]
Mega2R is now available again in CRAN.
